version: '3.8'

services:
  mysql:
    build: .
    container_name: mysql_container
    env_file:
      - ./env/.env.production
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    env_file:
      - ./env/.env.production
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
